version: "3.8"
services:
  web:
    build: .

    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
    - db
    environment:
    - FLASK_ENV=development
    env_file:
    - .env
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=Proyectocloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Talon1528
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: